image:https://api.travis-ci.org/meistermeier/neo4j-ogm-label-extension.svg?branch=master[build state]

== Static Label Extension for Neo4j-OGM

This projects provides a limited support for manipulating Cypher statements
 and add an additional label to all nodes in the statement.

=== Usage

Just add this library to your Neoj4-OGM based project and provide your label.
This can be done by defining it as a static `String` value

[source, java]
----
SessionFactory sessionFactory = new SessionFactory(
		new Configuration.Builder()
			.withConfigProperty(StaticLabelModificationProvider.CONFIGURATION_KEY, "StaticLabel")
			.build());
----

or a `Supplier` function

[source, java]
----
SessionFactory sessionFactory = new SessionFactory(
		new Configuration.Builder()
			.withConfigProperty(StaticLabelModificationProvider.CONFIGURATION_KEY, (Supplier) () -> "StaticLabel")
			.build());
----

=== Limitations
There are some limitations at the moment.

==== Tested support for 3.4.x only
This extension is built against Neo4j's `openCypher-frontend` and uses specific _3.4_ packages.
It may work with any other _3.1+_ version of Neo4j in server mode.

The current implementation has to override a lot of existing methods to generate the string representation of the manipulated Cypher statement.
That might break things in newer versions of openCypher.

If you are using this extension with an embedded Neo4j instance, it might end up in version conflicts regarding Scala, as there will be multiple Scala runtimes in your class path.

==== Limited keywords
Due to the fact that it is near to impossible to test against every possible statement, the extension only support some constructs right now.

NOTE: Also the conversion for the supported keywords themselves might be incomplete regarding its inner statements.

The keywords supported right now are:

* `Return`
* `Match`
* `With`
* `Create`
* `Unwind`
* `Set`
* `Delete`
* `Merge`
* _Custom procedure calls_
